name: POSIX Test
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_dispatch:

env:
  NO_COLOR: true
  CI: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # find ./packages/pjd-fstest/tests -type f -name '*.t'
        # Each file run (10.10.2023): https://github.com/divyenduz/zoid-fs/actions/runs/6471651605/job/17570542899
        tests:
          [
            "chflags",
            "chmod",
            "chown",
            "ftruncate",
            "link",
            "mkdir",
            "mkfifo",
            "mknod",
            "open",
            "rename",
            "rmdir",
            "symlink",
            "truncate",
            "unlink",
            "utime",
            "xacl",
          ]

    name: POSIX Test - ${{ matrix.tests }}
    timeout-minutes: 30
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Linux Libs
        run: sudo apt update && sudo apt install libfuse-dev build-essential libboost-all-dev cmake flex libacl1-dev

      - name: Install Dependencies
        run: npm install

      - name: Generate Types
        run: npm run generate

      - name: Run Lint
        run: npm run lint

      - name: Setup DB
        run: |
          npm run ci:setup-db
          cp packages/sqlite-backend/prisma/fs.db packages/sqlite-backend/prisma/test.db

      - name: Start FUSE Daemon
        run: |
          mkdir ${{ runner.temp }}/test-fs
          npm run ci:setup-fuse -- -- ${{ runner.temp }}/test-fs --tenant test &
          sleep 5
          df -h
          cd ${{ runner.temp }}
          tree -la

      - name: Setup fstest
        run: |
          cd packages/pjd-fstest
          make

      - name: fstest Description
        run: |
          if [ -f "${{ github.workspace }}/packages/pjd-fstest/tests/${{matrix.tests}}" ]; then
            cat ${{ github.workspace }}/packages/pjd-fstest/tests/${{matrix.tests}} | grep desc
          else
            echo "${{ matrix.tests }}/*"
          fi

      - name: Run fstest - ${{ matrix.tests }}
        run: |
          cd ${{ runner.temp }}/test-fs
          prove -r ${{ github.workspace }}/packages/pjd-fstest/tests/${{matrix.tests}}
