name: POSIX Test
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_dispatch:

env:
  NO_COLOR: true
  CI: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # find ./packages/pjd-fstest/tests -type f -name '*.t'
        tests:
          [
            "chflags/00.t",
            "chflags/01.t",
            "chflags/02.t",
            "chflags/03.t",
            "chflags/04.t",
            "chflags/05.t",
            "chflags/06.t",
            "chflags/07.t",
            "chflags/08.t",
            "chflags/09.t",
            "chflags/10.t",
            "chflags/11.t",
            "chflags/12.t",
            "chflags/13.t",
            "chmod/00.t",
            "chmod/01.t",
            "chmod/02.t",
            "chmod/03.t",
            "chmod/04.t",
            "chmod/05.t",
            "chmod/06.t",
            "chmod/07.t",
            "chmod/08.t",
            "chmod/09.t",
            "chmod/10.t",
            "chmod/11.t",
            "chown/00.t",
            "chown/01.t",
            "chown/02.t",
            "chown/03.t",
            "chown/04.t",
            "chown/05.t",
            "chown/06.t",
            "chown/07.t",
            "chown/08.t",
            "chown/09.t",
            "chown/10.t",
            "ftruncate/00.t",
            "ftruncate/13.t",
            "link/00.t",
            "link/01.t",
            "link/02.t",
            "link/03.t",
            "link/04.t",
            "link/05.t",
            "link/06.t",
            "link/07.t",
            "link/08.t",
            "link/09.t",
            "link/10.t",
            "link/11.t",
            "link/12.t",
            "link/13.t",
            "link/14.t",
            "link/15.t",
            "link/16.t",
            "link/17.t",
            "mkdir/00.t",
            "mkdir/01.t",
            "mkdir/02.t",
            "mkdir/03.t",
            "mkdir/04.t",
            "mkdir/05.t",
            "mkdir/06.t",
            "mkdir/07.t",
            "mkdir/08.t",
            "mkdir/09.t",
            "mkdir/10.t",
            "mkdir/11.t",
            "mkdir/12.t",
            "mkfifo/00.t",
            "mkfifo/01.t",
            "mkfifo/02.t",
            "mkfifo/03.t",
            "mkfifo/04.t",
            "mkfifo/05.t",
            "mkfifo/06.t",
            "mkfifo/07.t",
            "mkfifo/08.t",
            "mkfifo/09.t",
            "mkfifo/10.t",
            "mkfifo/11.t",
            "mkfifo/12.t",
            "mknod/00.t",
            "mknod/01.t",
            "mknod/02.t",
            "mknod/03.t",
            "mknod/04.t",
            "mknod/05.t",
            "mknod/06.t",
            "mknod/07.t",
            "mknod/08.t",
            "mknod/09.t",
            "mknod/10.t",
            "mknod/11.t",
            "open/00.t",
            "open/01.t",
            "open/02.t",
            "open/03.t",
            "open/04.t",
            "open/05.t",
            "open/06.t",
            "open/07.t",
            "open/08.t",
            "open/09.t",
            "open/10.t",
            "open/11.t",
            "open/12.t",
            "open/13.t",
            "open/14.t",
            "open/15.t",
            "open/16.t",
            "open/17.t",
            "open/18.t",
            "open/19.t",
            "open/20.t",
            "open/21.t",
            "open/22.t",
            "open/23.t",
            "rename/00.t",
            "rename/01.t",
            "rename/02.t",
            "rename/03.t",
            "rename/04.t",
            "rename/05.t",
            "rename/06.t",
            "rename/07.t",
            "rename/08.t",
            "rename/09.t",
            "rename/10.t",
            "rename/11.t",
            "rename/12.t",
            "rename/13.t",
            "rename/14.t",
            "rename/15.t",
            "rename/16.t",
            "rename/17.t",
            "rename/18.t",
            "rename/19.t",
            "rename/20.t",
            "rmdir/00.t",
            "rmdir/01.t",
            "rmdir/02.t",
            "rmdir/03.t",
            "rmdir/04.t",
            "rmdir/05.t",
            "rmdir/06.t",
            "rmdir/07.t",
            "rmdir/08.t",
            "rmdir/09.t",
            "rmdir/10.t",
            "rmdir/11.t",
            "rmdir/12.t",
            "rmdir/13.t",
            "rmdir/14.t",
            "rmdir/15.t",
            "symlink/00.t",
            "symlink/01.t",
            "symlink/02.t",
            "symlink/03.t",
            "symlink/04.t",
            "symlink/05.t",
            "symlink/06.t",
            "symlink/07.t",
            "symlink/08.t",
            "symlink/09.t",
            "symlink/10.t",
            "symlink/11.t",
            "symlink/12.t",
            "truncate/00.t",
            "truncate/01.t",
            "truncate/02.t",
            "truncate/03.t",
            "truncate/04.t",
            "truncate/05.t",
            "truncate/06.t",
            "truncate/07.t",
            "truncate/08.t",
            "truncate/09.t",
            "truncate/10.t",
            "truncate/11.t",
            "truncate/12.t",
            "truncate/13.t",
            "truncate/14.t",
            "unlink/00.t",
            "unlink/01.t",
            "unlink/02.t",
            "unlink/03.t",
            "unlink/04.t",
            "unlink/05.t",
            "unlink/06.t",
            "unlink/07.t",
            "unlink/08.t",
            "unlink/09.t",
            "unlink/10.t",
            "unlink/11.t",
            "unlink/12.t",
            "unlink/13.t",
            "utime/00.t",
            "utime/01.t",
            "utime/02.t",
            "utime/03.t",
            "utime/04.t",
            "xacl/00.t",
            "xacl/01.t",
            "xacl/02.t",
            "xacl/03.t",
            "xacl/04.t",
            "xacl/05.t",
            "xacl/06.t",
          ]

    name: POSIX Test - ${{ matrix.tests }}
    timeout-minutes: 30
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Linux Libs
        run: sudo apt update && sudo apt install libfuse-dev build-essential libboost-all-dev cmake flex libacl1-dev

      - name: Install Dependencies
        run: npm install

      - name: Generate Types
        run: npm run generate

      - name: Run Lint
        run: npm run lint

      - name: Setup DB
        run: |
          npm run ci:setup-db
          cp packages/sqlite-backend/prisma/fs.db packages/sqlite-backend/prisma/test.db

      - name: Start FUSE Daemon
        run: |
          mkdir ${{ runner.temp }}/test-fs
          npm run ci:setup-fuse -- -- ${{ runner.temp }}/test-fs --tenant test &
          sleep 5
          df -h
          cd ${{ runner.temp }}
          tree -la

      - name: Setup fstest
        run: |
          cd packages/pjd-fstest
          make

      - name: fstest Description
        run: |
          cat ${{ github.workspace }}/packages/pjd-fstest/tests/${{matrix.tests}} | grep desc

      - name: Run fstest - ${{ matrix.tests }}
        run: |
          cd ${{ runner.temp }}/test-fs
          prove -r ${{ github.workspace }}/packages/pjd-fstest/tests/${{matrix.tests}}
