name: Test
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_dispatch:

env:
  NO_COLOR: true
  CI: 1

jobs:
  build:
    name: Test
    timeout-minutes: 30
    runs-on: [ubuntu-latest]
    # runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Linux Libs
        run: sudo apt install libfuse-dev

      - name: Install Dependencies
        run: npm install

      - name: Generate Types
        run: npm run generate

      - name: Run Lint
        run: npm run lint

      - name: Setup DB
        run: |
          npm run ci:setup-db
          cp packages/sqlite-backend/prisma/fs.db packages/sqlite-backend/prisma/test.db

      - name: Start FUSE Daemon
        run: |
          mkdir ${{ runner.temp }}/test-fs
          npm run ci:setup-fuse -- -- ${{ runner.temp }}/test-fs --tenant test &
          sleep 5
          df -h
          cd ${{ runner.temp }}
          tree -la

      # - name: Run Tests
      #   run: npm run test
